# Netlify build configuration for Meridian Mastery
[build]
  # Build command - force clean install with optional deps for esbuild
  command = "npm ci --include=optional && npm run build"
  # Directory to publish (build output)
  publish = "dist"

# Node.js version (use LTS version)
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=optional"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
