# Netlify build configuration for Meridian Mastery
[build]
  # Build command - ensure all dependencies are installed
  command = "npm ci && npm run build"
  # Directory to publish (build output)
  publish = "dist"

# Node.js version (use LTS version)
[build.environment]
  NODE_VERSION = "18.18.0"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
