# Netlify build configuration for Meridian Mastery
[build]
  # Build command - clean install with esbuild fix
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  # Directory to publish (build output)
  publish = "dist"

# Node.js version (use LTS version)
[build.environment]
  NODE_VERSION = "18"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
