# Netlify build configuration for Meridian Mastery
[build]
  # Simple build command - let Netlify handle dependency management
  command = "npm run build"
  # Directory to publish (build output)
  publish = "dist"

# Node.js version (use LTS version)
[build.environment]
  NODE_VERSION = "18"

# SPA redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
